### ISSUE TITLE
gpgme failed to install

### ISSUE THREAD

**Issue by toshi0123** [toshi0123/docker-alpine-gitlab-ce#1]
error messages as follows.
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/gpgme-2.0.13/ext/gpgme
/usr/bin/ruby -r ./siteconf20171025-14-1ozpwln.rb extconf.rb
************************************************************************
IMPORTANT!  gpgme gem uses locally built versions of required C libraries,
namely libgpg-error, libassuan, and gpgme.

If this is a concern for you and you want to use the system library
instead, abort this installation process and reinstall gpgme gem as
follows:

    gem install gpgme -- --use-system-libraries

************************************************************************
Extracting libgpg-error-1.27.tar.bz2 into
tmp/x86_64-alpine-linux-musl/ports/libgpg-error/1.27... OK
Running 'configure' for libgpg-error 1.27... OK
Running 'compile' for libgpg-error 1.27... OK
Running 'install' for libgpg-error 1.27... OK
Activating libgpg-error 1.27 (from
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/gpgme-2.0.13/ports/x86_64-alpine-linux-musl/libgpg-error/1.27)...
Extracting libassuan-2.4.3.tar.bz2 into
tmp/x86_64-alpine-linux-musl/ports/libassuan/2.4.3... OK
Running 'configure' for libassuan 2.4.3... OK
Running 'compile' for libassuan 2.4.3... ERROR, review
'/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/gpgme-2.0.13/ext/gpgme/tmp/x86_64-alpine-linux-musl/ports/libassuan/2.4.3/compile.log'
to see what happened. Last lines are:
========================================================================
In file included from assuan.c:28:0:
assuan-defs.h:362:23: error: unknown type name 'cookie_read_function_t'
                       cookie_read_function_t *readfn,
                       ^~~~~~~~~~~~~~~~~~~~~~
assuan-defs.h:363:23: error: unknown type name 'cookie_write_function_t'
                       cookie_write_function_t *writefn,
                       ^~~~~~~~~~~~~~~~~~~~~~~
assuan-defs.h:364:23: error: unknown type name 'cookie_seek_function_t'
                       cookie_seek_function_t *seekfn,
                       ^~~~~~~~~~~~~~~~~~~~~~
assuan-defs.h:365:23: error: unknown type name 'cookie_close_function_t'
                       cookie_close_function_t *closefn);
                       ^~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [Makefile:709: libassuan_la-assuan.lo] Error 1
make[3]: Leaving directory
'/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/gpgme-2.0.13/ext/gpgme/tmp/x86_64-alpine-linux-musl/ports/libassuan/2.4.3/libassuan-2.4.3/src'
make[2]: *** [Makefile:480: all] Error 2
make[2]: Leaving directory
'/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/gpgme-2.0.13/ext/gpgme/tmp/x86_64-alpine-linux-musl/ports/libassuan/2.4.3/libassuan-2.4.3/src'
make[1]: *** [Makefile:443: all-recursive] Error 1
make[1]: Leaving directory
'/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/gpgme-2.0.13/ext/gpgme/tmp/x86_64-alpine-linux-musl/ports/libassuan/2.4.3/libassuan-2.4.3'
make: *** [Makefile:374: all] Error 2
========================================================================
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)
	--clean
	--use-system-libraries
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/mini_portile2-2.3.0/lib/mini_portile2/mini_portile.rb:402:in
`block in execute': Failed to complete compile task (RuntimeError)
from
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/mini_portile2-2.3.0/lib/mini_portile2/mini_portile.rb:373:in
`chdir'
from
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/mini_portile2-2.3.0/lib/mini_portile2/mini_portile.rb:373:in
`execute'
from
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/mini_portile2-2.3.0/lib/mini_portile2/mini_portile.rb:115:in
`compile'
from
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/mini_portile2-2.3.0/lib/mini_portile2/mini_portile.rb:154:in
`cook'
	from extconf.rb:99:in `block in <main>'
	from extconf.rb:85:in `tap'
	from extconf.rb:85:in `<main>'

extconf failed, exit code 1
```

**Comment by toshi0123** [comment]
https://qiita.com/thunders/items/101c6b329830fb1fb27d
