### ISSUE TITLE
gitlab-shell failed to rake

### ISSUE THREAD

**Issue by toshi0123** [toshi0123/docker-alpine-gitlab-ce#2]
error messages as follows.
```
LoadError: cannot load such file -- bigdecimal/util
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/core_ext/big_decimal/conversions.rb:2:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/core_ext/big_decimal/conversions.rb:2:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/core_ext/object/json.rb:4:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/core_ext/object/json.rb:4:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/core_ext/object.rb:12:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/core_ext/object.rb:12:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/configuration.rb:2:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/configuration.rb:2:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/railtie.rb:2:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/railtie.rb:2:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/engine.rb:1:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/engine.rb:1:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/application.rb:7:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/application.rb:7:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails.rb:11:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails.rb:11:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/all.rb:1:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/all.rb:1:in `<top (required)>'
/home/git/gitlab/config/application.rb:3:in `require'
/home/git/gitlab/config/application.rb:3:in `<top (required)>'
/home/git/gitlab/Rakefile:5:in `require'
/home/git/gitlab/Rakefile:5:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
/usr/bin/bundle:23:in `load'
/usr/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```

**Comment by toshi0123** [comment]
https://qiita.com/asmsuechan/items/6b00b92ae744c49cfd9c
above url's auther suggests to install ruby-bigdecimal.

**Comment by toshi0123** [comment]
another error of missing package
```
LoadError: cannot load such file -- irb/ruby-lex
```

**Comment by toshi0123** [comment]
another error of tzdata
```
TZInfo::DataSourceNotFound: No source of timezone data could be found.
```
