### ISSUE TITLE
gitaly failed to install

### ISSUE THREAD

**Issue by toshi0123** [toshi0123/docker-alpine-gitlab-ce#3]
error messages as follows.
```
** Invoke gitlab:gitaly:install (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute gitlab:gitaly:install
rake aborted!
Gitlab::TaskFailedError: env: invalid number 'RUBYOPT'
/home/git/gitlab/lib/tasks/gitlab/task_helpers.rb:86:in `run_command!'
/home/git/gitlab/lib/tasks/gitlab/gitaly.rake:28:in `block (5 levels) in <top (required)>'
/usr/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler.rb:293:in `block in with_original_env'
/usr/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler.rb:540:in `with_env'
/usr/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler.rb:293:in `with_original_env'
/home/git/gitlab/lib/tasks/gitlab/gitaly.rake:28:in `block (4 levels) in <top (required)>'
/home/git/gitlab/lib/tasks/gitlab/gitaly.rake:24:in `chdir'
/home/git/gitlab/lib/tasks/gitlab/gitaly.rake:24:in `block (3 levels) in <top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:251:in `block in execute'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:251:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:251:in `execute'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:181:in `invoke'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:153:in `invoke_task'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:109:in `block (2 levels) in top_level'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:109:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:109:in `block in top_level'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:118:in `run_with_threads'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:103:in `top_level'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:81:in `block in run'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:179:in `standard_exception_handling'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:78:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/bin/rake:23:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/bin/rake:23:in `<top (required)>'
/usr/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/cli/exec.rb:75:in `load'
/usr/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/cli/exec.rb:75:in `kernel_load'
/usr/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/cli/exec.rb:28:in `run'
/usr/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/cli.rb:424:in `exec'
/usr/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/cli.rb:27:in `dispatch'
/usr/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/cli.rb:18:in `start'
/usr/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/exe/bundle:30:in `block in <top (required)>'
/usr/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/usr/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/exe/bundle:22:in `<top (required)>'
/usr/bin/bundle:23:in `load'
/usr/bin/bundle:23:in `<main>'
Tasks: TOP => gitlab:gitaly:install
```

**Comment by toshi0123** [comment]
env command returns as follows.
```
# /usr/bin/env -u RUBYOPT -u BUNDLE_GEMFILE
env: invalid number 'RUBYOPT'
```
This error occurs when using busybox.
```
# /usr/bin/env --help
BusyBox v1.27.2 (2017-10-20 05:56:33 GMT) multi-call binary.

Usage: env [-iu] [-] [name=value]... [PROG ARGS]

Print the current environment or run PROG after setting up
the specified environment

        -, -i   Start with an empty environment
        -u      Remove variable from the environment
```

**Comment by toshi0123** [comment]
https://hub.docker.com/r/toshi0123/docker-alpine-gitlab-ce/builds/bv2gvaruqfsrk4wja6c2gx9/
